sudo: required
dist: trusty

services:
- docker

install:
- docker-compose -f docker-compose-testing.yml pull
- docker-compose -f docker-compose-testing.yml build

script:
- docker-compose -f docker-compose-testing.yml run -e DJANGO_SETTINGS_MODULE=config.testing --no-deps --rm backend py.test